services:
  db:
    image: postgres:16
    container_name: budget_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budget
    ports:
      - "5432:5432"
    volumes:
      - budget_data:/var/lib/postgresql/data

volumes:
  budget_data:
